import type { Guide } from './types'

/**
 * Restoration guides. Each is reference material written for enthusiasts, not a
 * vehicle-specific repair procedure. Safety-relevant guides carry an explicit warning.
 */
export const guides: Guide[] = [
  {
    slug: 'evaluating-a-classic-car',
    title: 'How to Evaluate a Classic Car Before Restoration',
    summary:
      'A structured way to work out what a project car will actually demand of you, before money changes hands.',
    stage: 'Assessment',
    difficulty: 'Introductory',
    image: 'blog-first-restoration',
    blocks: [
      { t: 'p', text: 'Evaluation is the highest-leverage hour in any restoration. Everything that follows — the budget, the timeline, whether the project finishes at all — is set by the condition of the car you start with. A car bought for two thousand dollars more, in materially better condition, is routinely cheaper to restore than the bargain alternative.' },
      { t: 'h2', text: 'Establish what the car is before you assess how good it is' },
      { t: 'p', text: 'Identity comes first. Locate and read the VIN, the body tag or trim tag, and any engine and transmission stampings. Compare them against published decoding references for the marque and year. This tells you the model, body style, original engine, original colour and trim, and the assembly plant. It also tells you whether the car in front of you is what the advertisement claimed.' },
      { t: 'p', text: 'This matters for two reasons. A car whose drivetrain is original to it — commonly described as numbers-matching — occupies a different market position from an otherwise identical car with a replacement engine. And a car being represented as a rare high-performance variant, when the tags say it left the factory as a base model, is a very different proposition.' },
      { t: 'h2', text: 'Assess structure before cosmetics' },
      { t: 'p', text: 'Get the car on a lift or on stands and look underneath with a strong light. On a unibody car you are inspecting floor pans, rocker panels, torque boxes, subframe mounting points and the shock towers. On a body-on-frame car you are inspecting the frame rails themselves, particularly at the kick-ups over the axle and at the crossmember mounts.' },
      { t: 'ul', items: [
        'Tap suspect areas firmly with a small hammer or screwdriver handle. Sound steel rings; compromised steel sounds dull and may give.',
        'Look for ripples, mismatched welds or seam sealer applied over the top of previous repairs.',
        'Check that the two sides of the car are symmetrical — a car that has been hit and pulled will not be.',
        'Open and close every door, and check the gaps. Doors that drop or bind often indicate a tired or repaired shell.',
      ]},
      { t: 'h2', text: 'Then the drivetrain' },
      { t: 'p', text: 'A non-running engine is not automatically a problem — a rebuild may well be planned anyway. What you are trying to establish is whether the engine is seized, whether it has been standing open to the weather, and whether it is the correct unit for the car. Pull the plugs and look for water staining. Try to turn the engine over by hand on the crankshaft bolt before ever connecting a battery.' },
      { t: 'h2', text: 'Count the parts that are missing' },
      { t: 'p', text: 'This is the step most first-time buyers skip, and it is the one that produces the nastiest surprises. Trim, badges, correct glass, dash components, seat frames, window regulators and factory-correct wheels are frequently harder and more expensive to source than sheet metal. A complete but rusty car is often a better starting point than a rust-free car that has been picked over.' },
      { t: 'callout', kind: 'note', title: 'Bring someone who has done it', text: 'If this is your first project, take an experienced restorer or an inspector with you. Their fee is trivial compared with the cost of the wrong car, and they will look at things you do not yet know to look at.' },
    ],
    checklist: [
      'VIN, body tag and drivetrain stampings recorded and decoded',
      'Underside inspected on a lift or stands with a strong light',
      'Floor pans, rockers, torque boxes and frame rails probed, not just looked at',
      'Panel gaps and door operation checked on both sides',
      'Engine turned by hand before any attempt to start it',
      'Complete inventory taken of missing trim, glass and interior parts',
      'Ownership paperwork and title status confirmed as clear',
      'Written estimate obtained for the two or three biggest known jobs',
    ],
    related: ['rust-inspection', 'frame-inspection', 'restoration-budget-planning'],
  },
  {
    slug: 'rust-inspection',
    title: 'Rust Inspection Guide',
    summary:
      'Where corrosion hides on American classics, how to tell cosmetic rust from structural rust, and what each means for the project.',
    stage: 'Assessment',
    difficulty: 'Introductory',
    image: 'blog-rust-inspection',
    blocks: [
      { t: 'p', text: 'Rust is not one condition. It is a spectrum running from a light bloom on a bare surface through to complete loss of the parent metal, and where a car sits on that spectrum determines whether you are looking at an afternoon or a year.' },
      { t: 'h2', text: 'The three stages' },
      { t: 'terms', items: [
        { term: 'Surface rust', def: 'Oxidation on the outer face of otherwise sound steel, usually where paint has been chipped or scratched. The panel retains its full thickness. Mechanically removable, then treatable.' },
        { term: 'Scale rust', def: 'Corrosion that has penetrated far enough to lift and flake the metal in layers. The panel has lost measurable thickness and strength. Repair usually means cutting out and replacing the affected section.' },
        { term: 'Penetrating rust', def: 'The metal has been consumed through its full thickness. Holes are present, whether or not you can see them from outside. There is nothing left to treat — the section must be replaced.' },
      ]},
      { t: 'h2', text: 'Where to look on American classics' },
      { t: 'p', text: 'Corrosion follows water, and water follows gravity into places that were never designed to drain properly. The pattern is consistent across most American cars of the 1950s through 1970s.' },
      { t: 'ul', items: [
        'Lower rear quarter panels, especially the area ahead of the rear wheel and behind it.',
        'Wheel arch lips and the inner wheel houses behind them.',
        'Floor pans, worst under the front footwells where cowl leaks drain.',
        'The cowl and plenum chamber, a chronic weak point where leaves and water collect out of sight.',
        'Trunk floors, spare wheel wells and the rear valance.',
        'Rocker panels, and the inner rocker structure that actually carries the load.',
        'Door bottoms, where the drain holes block and water stands inside the skin.',
        'Around the front and rear window apertures, under the trim, where seals have failed.',
      ]},
      { t: 'h2', text: 'How to inspect properly' },
      { t: 'ol', items: [
        'Work with a strong torch and, ideally, an inspection mirror or a borescope for enclosed sections.',
        'Use a small magnet wrapped in cloth. Weak or no attraction indicates filler rather than steel beneath the paint.',
        'Tap along suspect seams. Listen for the change from a sharp ring to a dull thud.',
        'Pull up carpet and lift the trunk mat. Do not accept a seller telling you the floors are fine.',
        'Look at the underside from below, not just from inside the cabin.',
        'Photograph everything you find, with a scale reference, so you can price the repair later.',
      ]},
      { t: 'callout', kind: 'caution', title: 'Undercoating deserves suspicion', text: 'Thick, freshly applied undercoating on a car being sold is worth investigating rather than admiring. It is an effective way to conceal both perforation and previous repair. Probe it in several places.' },
      { t: 'h2', text: 'Reading what you find' },
      { t: 'p', text: 'Cosmetic corrosion on outer skins is bounded work with a fairly predictable cost. Structural corrosion is different in kind: it affects how the car carries load, how it behaves in a collision, and in many jurisdictions whether it can be registered for road use at all. A car with rotten floors and rockers is not a car that needs paint — it is a car that needs fabrication.' },
    ],
    checklist: [
      'Floor pans checked from above and below, carpet lifted',
      'Rockers and inner rocker structure probed along their full length',
      'Trunk floor and spare wheel well inspected with the mat removed',
      'Cowl and plenum drains checked for blockage',
      'Magnet test performed across all lower panels',
      'Frame rails or torque boxes examined at every mounting point',
      'Window aperture edges checked beneath the trim where accessible',
      'All findings photographed for later costing',
    ],
    safety: 'Never work under a vehicle supported only by a jack. Use rated axle stands on a level, solid surface, and check stability before going underneath.',
    related: ['evaluating-a-classic-car', 'body-panel-repair', 'frame-inspection'],
  },
  {
    slug: 'frame-inspection',
    title: 'Frame Inspection',
    summary:
      'How body-on-frame and unibody American cars differ structurally, and what to check on each before committing.',
    stage: 'Assessment',
    difficulty: 'Intermediate',
    image: 'blog-frame-off',
    blocks: [
      { t: 'p', text: 'American cars of the classic era were built both ways, and the distinction changes what you inspect and what a repair costs. Full-size cars, trucks and many earlier models used a separate ladder frame carrying a bolted-on body. Most intermediates and pony cars from the mid-1960s onward used unibody construction, sometimes with a bolt-on front subframe.' },
      { t: 'h2', text: 'Body-on-frame' },
      { t: 'p', text: 'Here the frame is the structure, and the body is cargo. That is good news in one respect: a rotten body sitting on a sound frame is a bounded problem. Inspect the rails along their full length, paying particular attention to the kick-ups over the rear axle, the areas around body mounts, and any point where a crossmember attaches. Corrosion inside a boxed rail can be advanced while the outside still looks acceptable, so probe from underneath and look inside through factory access holes where they exist.' },
      { t: 'h2', text: 'Unibody' },
      { t: 'p', text: 'On a unibody car, the floor pans, rockers, torque boxes and inner structure are the frame. There is no separate chassis to fall back on. That means corrosion in the floors is a structural finding, not a cosmetic one, and repairs must restore the original load paths — which is why replacement sections are welded in to duplicate the factory spot-weld pattern rather than simply patched over.' },
      { t: 'h2', text: 'Checking for accident damage' },
      { t: 'ul', items: [
        'Measure diagonally between matching reference points on each side. A square structure gives equal diagonals.',
        'Look for wrinkles or ripples in frame rails, inner fenders and floor pans — these do not occur naturally.',
        'Check for weld spatter, grinding marks or paint overspray in areas the factory never painted.',
        'Compare fastener heads left and right. Disturbed factory bolts on one side only tell a story.',
        'Sight along the body from front to rear at a low angle to reveal misalignment.',
      ]},
      { t: 'callout', kind: 'note', title: 'When to bring in a body shop', text: 'A shop with a frame machine and a measuring system can compare the car against factory dimensional data and tell you definitively whether the structure is straight. If a car is otherwise attractive but you suspect damage, that measurement is worth paying for before purchase.' },
      { t: 'h2', text: 'Frame-off versus frame-on' },
      { t: 'p', text: 'A frame-off restoration separates body from chassis so both can be restored and refinished completely. It produces the most thorough result and is the standard for concours work. It also multiplies labour, requires storage and lifting equipment, and pushes a project into a different scale entirely. Frame-on restoration, where the body stays attached, is the right choice for a great many cars, and produces an honest, usable vehicle without pretending to be something it is not.' },
    ],
    checklist: [
      'Frame rails inspected along their full length, inside and out',
      'Body mount points and crossmember attachments checked',
      'Diagonal measurements compared side to side',
      'Inner fenders, rails and floors checked for ripples or wrinkles',
      'Evidence of previous repair identified and understood',
      'Torque boxes and subframe connections checked on unibody cars',
      'Decision recorded on frame-off versus frame-on before work begins',
    ],
    safety: 'Separating a body from a frame requires appropriate lifting equipment and rated supports. This is not a job to improvise with household jacks or timber.',
    related: ['rust-inspection', 'evaluating-a-classic-car', 'suspension-restoration'],
  },
  {
    slug: 'engine-rebuild-basics',
    title: 'Engine Rebuild Basics',
    summary:
      'What a rebuild actually involves, which steps genuinely cannot be skipped, and where the money goes.',
    stage: 'Mechanical',
    difficulty: 'Advanced',
    image: 'engine-gto-389-tripower',
    blocks: [
      { t: 'p', text: 'The phrase "engine rebuild" covers everything from new rings and bearings on a still-serviceable block through to a complete machined rebuild with new rotating assembly. Being precise about which one you mean is the first step in budgeting for it.' },
      { t: 'h2', text: 'Establish what you have' },
      { t: 'p', text: 'Record casting numbers on the block and heads, casting dates, and any stamped identification pad. These establish whether the engine is the type the car left the factory with, and in some cases whether it is the actual unit. Photograph everything before disassembly, and bag and label fasteners by location.' },
      { t: 'h2', text: 'Disassembly and inspection' },
      { t: 'ol', items: [
        'Drain fluids and remove ancillaries, keeping brackets with the components they carry.',
        'Remove heads, then the oil pan, then the rotating assembly, keeping bearing shells in order.',
        'Read the bearing shells. Wear patterns record how the engine was running and often why it failed.',
        'Measure cylinder bores for taper and out-of-round before deciding on machining.',
        'Send the block and heads for cleaning, then crack testing, before spending anything further.',
      ]},
      { t: 'h2', text: 'Machining' },
      { t: 'p', text: 'This is normally the largest line item. Depending on findings it may include boring and honing cylinders, decking the block, resurfacing heads, align-honing main bearing bores, grinding or polishing the crankshaft, reconditioning connecting rods, and a valve job on the heads. Balancing the rotating assembly is optional on a mild build and worthwhile on anything that will see sustained higher revolutions.' },
      { t: 'h2', text: 'Assembly discipline' },
      { t: 'p', text: 'Assembly happens in a clean space, with clean parts, and with everything measured rather than assumed.' },
      { t: 'ul', items: [
        'Measure bearing clearances on the parts actually being used, not from the specification sheet alone.',
        'Check piston ring end gaps in the specific bore each ring will run in.',
        'Verify piston-to-valve clearance whenever a camshaft, head or piston has changed.',
        'Follow the manufacturer torque sequence and figures; use stretch figures for rod bolts where specified.',
        'Prime the oil system before the first start so bearings are not run dry.',
      ]},
      { t: 'callout', kind: 'cost', title: 'Where budgets break', text: 'Machine shop labour frequently exceeds the cost of the parts. Get a written quotation covering the likely operations before the block leaves your workshop, and agree what happens — and what it costs — if crack testing finds a problem.' },
      { t: 'callout', kind: 'safety', title: 'This is specialist work', text: 'Engine assembly carries real consequences when it goes wrong, including fire and mechanical failure at speed. Machining must be done by a qualified shop. If you are not confident measuring clearances to a thousandth of an inch, have the short block professionally assembled — many shops will do exactly that and let you complete the rest.' },
    ],
    checklist: [
      'Casting numbers and date codes recorded and photographed',
      'Bearing shells read and wear pattern interpreted',
      'Block and heads crack tested before machining is paid for',
      'Written machine shop quotation obtained',
      'Bearing clearances individually measured at assembly',
      'Ring end gaps checked in their own bores',
      'Torque sequences and figures taken from the correct manual',
      'Oil system primed before first start',
      'Break-in procedure agreed and followed, particularly for a flat-tappet camshaft',
    ],
    safety: 'Engine work involves heavy components, flammable liquids and stored energy in valve springs. Use correct lifting equipment, rated stands and appropriate eye protection, and have a suitable fire extinguisher within reach at first start.',
    related: ['transmission-restoration', 'brake-system-restoration', 'original-vs-reproduction-parts'],
  },
  {
    slug: 'transmission-restoration',
    title: 'Transmission Restoration',
    summary:
      'Manual and automatic transmissions in American classics, what typically fails, and when a rebuild is the right call.',
    stage: 'Mechanical',
    difficulty: 'Advanced',
    image: 'engine-amx-290',
    blocks: [
      { t: 'p', text: 'Transmissions are frequently the last thing considered and the first thing to spoil a finished car. A freshly restored vehicle that jumps out of gear, or shifts harshly, undermines everything else that was done well.' },
      { t: 'h2', text: 'Manual transmissions' },
      { t: 'p', text: 'The common wear items are synchroniser rings, bearings, and the shift linkage. Symptoms are readable: a crunch on a specific downshift usually points at that gear\'s synchro; a whine that changes with road speed rather than engine speed usually points at bearings; jumping out of gear under load often means worn shift forks, weak detents, or wear on the gear engagement teeth themselves.' },
      { t: 'p', text: 'Clutch work is normally bundled in, because the labour to access it overlaps almost entirely. Replacing the disc, pressure plate, release bearing and pilot bearing while the transmission is out is standard practice, and having the flywheel resurfaced at the same time is inexpensive insurance.' },
      { t: 'h2', text: 'Automatic transmissions' },
      { t: 'p', text: 'Period American automatics are robust designs, but the friction material, seals and the torque converter all age. Fluid that is dark and smells burnt is telling you the clutch packs have been slipping. Delayed engagement when selecting drive, or a flare between shifts, points to internal leakage past worn seals.' },
      { t: 'p', text: 'An automatic rebuild is genuinely specialist work requiring specific tools and a clean environment. For most owners the sensible route is a reputable transmission shop, ideally one that knows the specific unit — the differences between period American automatics matter, and a shop that works on them regularly will have the right parts and the right shim stock.' },
      { t: 'h2', text: 'Before you rebuild anything' },
      { t: 'ul', items: [
        'Confirm the fluid level and condition; some faults are simply low or degraded fluid.',
        'On automatics, check and adjust the shift linkage and any kickdown or vacuum modulator connection.',
        'On manuals, check the clutch adjustment and the condition of the linkage or hydraulic circuit.',
        'Verify the mounts. A collapsed transmission mount produces symptoms that mimic internal wear.',
      ]},
      { t: 'callout', kind: 'note', title: 'Match the transmission to the car', text: 'If originality matters, confirm the casting and identification numbers before rebuilding — or before buying a replacement unit. A correct-code transmission is part of a documented car\'s value.' },
    ],
    checklist: [
      'Fluid level and condition assessed before any diagnosis',
      'Linkage, mounts and adjustments checked and eliminated',
      'Transmission identification numbers recorded',
      'Clutch components replaced together on a manual rebuild',
      'Flywheel inspected and resurfaced as required',
      'Rear main seal condition addressed while access is available',
      'Correct fluid specification confirmed for the unit',
    ],
    safety: 'Transmissions are heavy and awkward. Use a proper transmission jack and rated stands; never balance a unit on a trolley jack or support a vehicle on blocks while working beneath it.',
    related: ['engine-rebuild-basics', 'preparing-for-road-use', 'parts-sourcing'],
  },
  {
    slug: 'brake-system-restoration',
    title: 'Brake System Restoration',
    summary:
      'Restoring drum and early disc systems on American classics, and the case for and against modern upgrades.',
    stage: 'Mechanical',
    difficulty: 'Intermediate',
    image: 'camaro-68-front',
    blocks: [
      { t: 'p', text: 'On a car that has been standing, assume the entire hydraulic system needs attention. Rubber components perish with age rather than mileage, and a car with fifteen thousand miles that has sat for twenty years is in worse hydraulic condition than one driven regularly.' },
      { t: 'h2', text: 'What gets replaced' },
      { t: 'ul', items: [
        'Flexible hoses, without exception. They perish internally and can trap pressure at the wheel.',
        'Wheel cylinders and caliper seals, or the complete units where rebuilding is uneconomic.',
        'The master cylinder, which is frequently pitted internally after long storage.',
        'Steel brake lines wherever there is corrosion, and preferably as a complete set.',
        'Shoes and pads, and the hardware kits — springs, retainers and adjusters — that come with them.',
      ]},
      { t: 'h2', text: 'Drums done properly work' },
      { t: 'p', text: 'There is a persistent assumption that drum brakes are inadequate. A correctly restored four-wheel drum system, with drums turned true and within limits, correct shoes, functioning self-adjusters and proper initial adjustment, will stop the car as designed. What produces poor drum braking is almost always neglect: glazed shoes, out-of-round drums, seized adjusters and stretched springs.' },
      { t: 'h2', text: 'The single-circuit question' },
      { t: 'p', text: 'Many American cars before the late 1960s used a single-circuit master cylinder, meaning one hydraulic failure anywhere takes away all braking at once. Dual-circuit conversion splits the system so a single failure leaves partial braking. This is one of the few modifications that a great many restorers, including originality-minded ones, consider on a car intended for regular road use. It is a decision to make consciously, with an understanding of how it affects both originality and, in some regions, compliance.' },
      { t: 'callout', kind: 'safety', title: 'Verify before you drive', text: 'After any brake work, bleed the system thoroughly, check for leaks under pressure with the engine running where a booster is fitted, and test at low speed in a safe, controlled space before using the road. If you are not equipped to verify the work, have it inspected by a qualified professional. Brakes are not an area where a hopeful outcome is acceptable.' },
      { t: 'callout', kind: 'caution', title: 'Old brake dust', text: 'Brake friction material fitted before the phase-out of asbestos may contain it. Never clean brake components with compressed air. Use appropriate wet methods and follow local regulations for handling and disposal.' },
    ],
    checklist: [
      'All flexible hoses replaced regardless of appearance',
      'Master cylinder inspected internally, replaced or professionally sleeved',
      'Wheel cylinders and calipers rebuilt or replaced',
      'Drums measured against the maximum diameter cast into them',
      'Rotors measured for thickness and runout',
      'Self-adjusters freed, lubricated and confirmed working',
      'System bled fully and checked for leaks under pressure',
      'Low-speed brake test carried out off the public road',
    ],
    safety: 'Brake work directly affects the safety of the vehicle and everyone around it. Support the vehicle on rated axle stands, and if you have any doubt about the work or your ability to verify it, use a qualified professional.',
    related: ['suspension-restoration', 'preparing-for-road-use', 'frame-inspection'],
  },
  {
    slug: 'suspension-restoration',
    title: 'Suspension Restoration',
    summary:
      'Bushings, ball joints, springs and geometry — restoring the parts that decide how a classic actually drives.',
    stage: 'Mechanical',
    difficulty: 'Intermediate',
    image: 'garage-hotrod-roadster',
    blocks: [
      { t: 'p', text: 'Suspension is where a restored car either feels solid or feels its age. It is also where the difference between replacing parts and restoring a system becomes obvious, because geometry matters as much as components.' },
      { t: 'h2', text: 'The standard wear list' },
      { t: 'ul', items: [
        'Control arm bushings, which harden, crack and allow the geometry to move under load.',
        'Ball joints, which develop play and are a genuine safety item when badly worn.',
        'Tie rod ends and idler arms, the usual cause of vague steering in period American cars.',
        'Shock absorbers, which almost always need replacement on a long-stored car.',
        'Coil or leaf springs, which sag over decades and change ride height and geometry.',
        'Sway bar bushings and end links, cheap parts that noticeably affect body control.',
      ]},
      { t: 'h2', text: 'Rubber, polyurethane or original specification' },
      { t: 'p', text: 'Rubber bushings reproduce the original ride quality and isolation. Polyurethane is more durable and locates the suspension more precisely, at the cost of transmitting more noise and vibration into the cabin, and it needs correct lubrication at installation. Neither is universally right. A car being restored to original specification wants rubber; a car built to be driven enthusiastically may prefer polyurethane in selected locations.' },
      { t: 'h2', text: 'Ride height and alignment' },
      { t: 'p', text: 'New springs change ride height, and ride height changes camber and caster. Any suspension work should be followed by a four-wheel alignment carried out to the factory specification for the car, by a shop willing to work to figures from a period service manual rather than whatever their machine suggests. Getting this wrong produces a car that wanders, wears tyres unevenly, and never quite feels settled.' },
      { t: 'callout', kind: 'safety', title: 'Springs store enormous energy', text: 'Coil springs — particularly on front suspension — hold sufficient stored energy to cause serious or fatal injury if released uncontrolled. Use a proper spring compressor rated for the application and follow its instructions exactly, or have the work done professionally. Torsion bars and leaf spring assemblies deserve the same respect.' },
    ],
    checklist: [
      'All bushings inspected with the suspension both loaded and unloaded',
      'Ball joints and tie rod ends checked for play',
      'Shock absorbers tested and replaced as a set per axle',
      'Ride height measured and compared with factory specification',
      'Bushing material chosen deliberately for the car\'s intended use',
      'Four-wheel alignment performed to period factory figures',
      'Fasteners torqued with the suspension at normal ride height where specified',
    ],
    safety: 'Spring compression, component weight and the need to work beneath the vehicle all make this a job requiring proper equipment. Use rated axle stands and a correct spring compressor, or use a professional workshop.',
    related: ['brake-system-restoration', 'frame-inspection', 'preparing-for-road-use'],
  },
  {
    slug: 'classic-car-electrical-systems',
    title: 'Classic Car Electrical Systems',
    summary:
      'Understanding period wiring, why grounds cause most faults, and how to decide between repair and a new harness.',
    stage: 'Electrical',
    difficulty: 'Intermediate',
    image: 'interior-rambler-770',
    blocks: [
      { t: 'p', text: 'Classic American electrical systems are straightforward in principle. The difficulty is almost never the original design — it is what six decades of owners have added to it.' },
      { t: 'h2', text: 'Know the system before you touch it' },
      { t: 'p', text: 'Many American cars built before the mid-1950s used 6-volt electrical systems, and some used positive earth. The industry transitioned to 12-volt negative earth during that decade. Establish which system the car actually has — not which one you assume it has — before connecting a battery, a charger or any accessory. Getting this wrong damages components immediately.' },
      { t: 'h2', text: 'Grounds cause most mysteries' },
      { t: 'p', text: 'A remarkable share of apparently baffling faults — dim lights, a gauge that reads wrong, a horn that sounds weak, a starter that clicks — come down to a poor earth connection. Current returning to the battery must pass through the body and chassis, and every paint layer, every rusted contact face and every corroded strap adds resistance.' },
      { t: 'ul', items: [
        'Clean each earth point back to bright metal, fit a star washer, and protect the joint afterwards.',
        'Confirm the engine-to-body and body-to-chassis earth straps exist and are in good condition.',
        'Add earth points where the factory was optimistic, particularly for rear lighting.',
      ]},
      { t: 'h2', text: 'Repair or replace the harness' },
      { t: 'p', text: 'Reproduction harnesses for popular models are made to original patterns, with correct colours and connectors. Replacement makes sense where the original insulation has gone brittle, where previous owners have spliced heavily, or where there has been a fire. Careful circuit-by-circuit repair makes sense where the loom is genuinely sound and the car is a preservation candidate.' },
      { t: 'h2', text: 'Fusing and added accessories' },
      { t: 'p', text: 'Period fuse blocks were sized for period loads. Electric fuel pumps, electric fans, modern audio and auxiliary lighting all need their own properly rated protection taken from a suitable supply, not tapped into a convenient existing circuit. Any added circuit should be fused as close to its power source as practical.' },
      { t: 'callout', kind: 'safety', title: 'Electrical faults start fires', text: 'Disconnect the battery — earth lead first — before working on wiring. Do not exceed the rated capacity of a circuit, never substitute a higher-rated fuse to stop one blowing, and keep wiring clear of exhaust components and moving parts. Where fuel system wiring is involved, or where you are unsure, use a qualified auto electrician.' },
    ],
    checklist: [
      'System voltage and polarity confirmed before any connection',
      'All earth points cleaned to bright metal and protected',
      'Engine, body and chassis earth straps verified',
      'Brittle or previously spliced wiring identified and replaced',
      'Every added accessory traced and correctly fused',
      'Wiring routed clear of heat and moving parts, and properly secured',
      'Wiring diagram for the specific year and model obtained',
    ],
    safety: 'Disconnect the battery before starting. Batteries vent flammable hydrogen and can deliver enough current to ignite a fire through a dropped tool.',
    related: ['preparing-for-road-use', 'interior-restoration', 'engine-rebuild-basics'],
  },
  {
    slug: 'paint-preparation',
    title: 'Paint Preparation',
    summary:
      'Stripping, priming and blocking — the stages that decide the final finish long before colour is mixed.',
    stage: 'Finishing',
    difficulty: 'Advanced',
    image: 'paint-impala-63',
    blocks: [
      { t: 'p', text: 'A paint finish is a thin film that faithfully reproduces whatever is underneath it. All of the quality is built in preparation; the spray gun merely records the result.' },
      { t: 'h2', text: 'Stripping to a known starting point' },
      { t: 'p', text: 'Repainting over unknown layers is a gamble. Old finishes may be incompatible with modern materials, may already be lifting, and will certainly hide what the metal is doing. Media blasting, chemical stripping and mechanical sanding each have a place, and each has drawbacks — blasting can warp thin panels if done aggressively, chemical strippers must be neutralised completely, particularly around seams.' },
      { t: 'h2', text: 'The primer sequence' },
      { t: 'ol', items: [
        'Epoxy primer directly on clean bare metal, for corrosion protection and adhesion.',
        'Body filler where needed, applied over epoxy rather than bare steel, and kept thin.',
        'High-build primer-surfacer, applied in sufficient coats to allow blocking without breaking through.',
        'Guide coat, a contrasting dusting that reveals highs and lows as you sand.',
        'Block sanding with progressively finer grades until the panel reads perfectly straight.',
        'Sealer, giving a uniform base colour and a consistent surface for the topcoat.',
      ]},
      { t: 'h2', text: 'Blocking is the job' },
      { t: 'p', text: 'This is where the hours are, and where the difference between an acceptable finish and an excellent one is made. Use a rigid block appropriate to the panel\'s shape, work in a cross-hatch pattern, and keep reapplying guide coat. The panel is finished when the guide coat is gone uniformly and the reflection of a straight edge stays straight as you move along it.' },
      { t: 'callout', kind: 'safety', title: 'Respiratory protection is non-negotiable', text: 'Two-pack primers and clearcoats contain isocyanates, which can cause permanent respiratory sensitisation from a single significant exposure. Cartridge masks do not protect against them. Safe application requires supplied-air breathing equipment and proper booth extraction. Sanding old finishes may also release lead from period paints. For most home restorers, this is the stage to hand to a professional shop.' },
      { t: 'callout', kind: 'note', title: 'Decide the target finish early', text: 'A concours-correct car may want the softer gloss and light orange peel of a period-appropriate finish. A driver may want a modern basecoat/clearcoat. The two require different materials and different preparation, so the decision needs making before primer, not after.' },
    ],
    checklist: [
      'Old finish removed to a known, sound substrate',
      'Bare metal sealed with epoxy primer without delay',
      'Filler applied thinly, over primer, and shaped rather than built up',
      'Sufficient high-build applied to survive blocking',
      'Guide coat used at every blocking stage',
      'Panels checked for straightness under a reflected light source',
      'Correct respiratory and skin protection in use throughout',
      'Colour verified against the car\'s original paint code where originality matters',
    ],
    safety: 'Modern automotive paint materials are hazardous to breathe and to touch. Use supplied-air respiratory protection, proper extraction, and appropriate gloves and coveralls, or use a professional refinishing facility.',
    related: ['body-panel-repair', 'chrome-restoration', 'rust-inspection'],
  },
  {
    slug: 'body-panel-repair',
    title: 'Body Panel Repair',
    summary:
      'Cutting out corrosion, fitting replacement steel, and the difference between a repair that lasts and one that reappears.',
    stage: 'Bodywork',
    difficulty: 'Advanced',
    image: 'blog-frame-off',
    blocks: [
      { t: 'p', text: 'Panel repair is where a restoration is won or lost structurally. A well-executed repair restores the original strength and geometry of the section; a poor one hides the problem for a few years and then telegraphs through fresh paint.' },
      { t: 'h2', text: 'Assess before cutting' },
      { t: 'p', text: 'Establish the true extent of the corrosion. Rust travels along seams and into enclosed sections, so the visible damage is usually smaller than the actual damage. Remove undercoating and seam sealer from the area, and probe the surrounding metal until you reach material that is genuinely sound. Cut back to that.' },
      { t: 'h2', text: 'Choosing replacement steel' },
      { t: 'ul', items: [
        'Full panels — best fit, highest cost, most disassembly, most welding.',
        'Partial or patch panels — cover common rust areas at lower cost; fit quality varies widely by supplier.',
        'Hand-fabricated sections — necessary for models with no reproduction support, and require real skill.',
      ]},
      { t: 'p', text: 'Reproduction panel quality is genuinely variable. Stamping accuracy, metal gauge and the crispness of body lines differ substantially between manufacturers, and the cheapest option frequently costs more in fitting labour than it saves in purchase price. Ask other restorers of the same model which supplier they use.' },
      { t: 'h2', text: 'Joining methods' },
      { t: 'p', text: 'Butt welding produces the strongest and most invisible joint, with the two edges meeting exactly and the weld dressed flush. Lap joints are easier but create a trap for moisture that will corrode from the inside. Where the factory used spot welds, duplicating that pattern with plug welds maintains the original load path and appearance. Whatever the method, the back side of every seam must be sealed and protected afterwards — a weld that is bare on the inside will rust from the inside.' },
      { t: 'callout', kind: 'caution', title: 'Filler is a shaping material, not a repair material', text: 'Body filler exists to smooth minor surface irregularities, typically a couple of millimetres at most. It is not a substitute for metalwork. Filler used to bridge a gap or fill a hole will crack, absorb moisture and fail, taking the paint with it.' },
      { t: 'callout', kind: 'safety', title: 'Welding and cutting hazards', text: 'Welding produces intense ultraviolet light, sparks and fumes. Use a correct-shade welding helmet, appropriate protective clothing, and proper ventilation or fume extraction. Remove or shield fuel lines, the fuel tank, and interior trim before striking an arc, and keep a suitable fire extinguisher immediately to hand. Coatings and old primers may release hazardous fumes when heated.' },
    ],
    checklist: [
      'Full extent of corrosion established before cutting',
      'Replacement panel test-fitted before any welding',
      'Body lines and panel gaps checked against the opposite side',
      'Butt joints used where appearance and strength both matter',
      'Factory spot-weld pattern duplicated where applicable',
      'Back side of every weld cleaned, sealed and protected',
      'Filler kept thin and used only for final shaping',
      'Fuel system and trim protected or removed before welding',
    ],
    safety: 'Welding near fuel lines, fuel tanks or upholstery risks fire. Remove or fully shield them, ventilate the workspace, wear proper protection and keep an extinguisher within reach.',
    related: ['rust-inspection', 'paint-preparation', 'frame-inspection'],
  },
  {
    slug: 'interior-restoration',
    title: 'Interior Restoration',
    summary:
      'Upholstery, headliners, carpet and dashboards — restoring the part of the car the owner actually lives in.',
    stage: 'Interior',
    difficulty: 'Intermediate',
    image: 'interior-corvette-53',
    blocks: [
      { t: 'p', text: 'Interior work is unusually visible. Every seam sits at eye level and every colour mismatch is noticed. It is also the area where careful conservation of original material is often more valuable than replacement.' },
      { t: 'h2', text: 'Document before you disturb' },
      { t: 'p', text: 'Photograph everything, from multiple angles, including how panels overlap, where clips sit, and how wiring is routed behind trim. Bag fasteners by location and label them. Interiors come apart in an order that is not obvious in reverse, and clips for period cars can be difficult to source once broken.' },
      { t: 'h2', text: 'Working order' },
      { t: 'ol', items: [
        'Seats out, then trim panels, then carpet, then sound deadening.',
        'Deal with the floor now — this is when corrosion is found and it changes the schedule.',
        'Fit new insulation and sound deadening before any soft trim returns.',
        'Headliner first, because installing it later means removing things you have just fitted.',
        'Carpet, shaped and trimmed carefully around every mounting point.',
        'Door and quarter trim, then seats, then dashboard components and instruments.',
      ]},
      { t: 'h2', text: 'Seats: cover and foam together' },
      { t: 'p', text: 'Replacing an upholstery cover over collapsed foam wastes the cover. New foam is inexpensive relative to the labour of dismantling a seat, and it is the difference between a seat that looks right and one that sags within a season. Check the frame and springs while it is apart, and address any rust or broken hog rings then.' },
      { t: 'h2', text: 'Dashboards and instruments' },
      { t: 'p', text: 'Original dash pads are among the harder parts to replace on many models, and reproductions vary in grain and fit. Where an original is intact, careful cleaning and conservation is usually the better answer. Instruments can often be restored — faces reprinted, mechanisms serviced, lenses polished — by specialists who do exactly this work.' },
      { t: 'callout', kind: 'note', title: 'Originality is a one-way decision', text: 'A complete, original interior in a preserved car cannot be recreated once it is thrown away. Where material is intact but tired, cleaning and repair keep an option open that replacement closes permanently.' },
    ],
    checklist: [
      'Full photographic record made before disassembly',
      'Fasteners and clips bagged and labelled by location',
      'Floor condition assessed with the interior stripped',
      'Sound deadening and insulation renewed before soft trim',
      'Seat foam replaced together with covers',
      'Seat frames and springs inspected and repaired',
      'Headliner fitted before carpet and trim',
      'Original dash pad and instruments conserved where viable',
    ],
    related: ['glass-and-weatherstripping', 'documentation-and-photography', 'classic-car-electrical-systems'],
  },
  {
    slug: 'chrome-restoration',
    title: 'Chrome Restoration',
    summary:
      'Rechroming, polishing and the realities of restoring the brightwork that defines American car design.',
    stage: 'Finishing',
    difficulty: 'Intermediate',
    image: 'paint-cadillac-59',
    blocks: [
      { t: 'p', text: 'Brightwork is central to the look of American cars of the 1950s and 1960s. It is also expensive, slow, and one of the most commonly underestimated lines in a restoration budget.' },
      { t: 'h2', text: 'Understanding what "chrome" means' },
      { t: 'p', text: 'Show-quality plating is a multi-layer process: the base metal is stripped and repaired, then copper plated and polished — often repeatedly — to eliminate pitting, then nickel plated for corrosion resistance and depth of shine, then finished with a thin layer of chromium. The visible chromium layer is very thin; virtually all of the appearance comes from the preparation and the copper and nickel beneath.' },
      { t: 'p', text: 'This is why quality plating costs what it does, and why cheap plating looks acceptable initially and then deteriorates. If the copper stage was rushed, pitting reappears through the surface within a year or two.' },
      { t: 'h2', text: 'Not everything is chrome-plated steel' },
      { t: 'ul', items: [
        'Bumpers and heavy trim on period American cars are typically plated steel.',
        'Die-cast zinc parts — many grilles, mirror housings and interior escutcheons — are more fragile, can pit deeply, and are harder and costlier to restore.',
        'Anodised aluminium trim is polished and re-anodised, not plated, and is destroyed by attempting to chrome it.',
        'Stainless steel trim is polished rather than plated and can often be restored in-house.',
      ]},
      { t: 'p', text: 'Sorting parts by material before sending anything out saves money and prevents damage. A competent plater will do this, but knowing what you have lets you have the conversation.' },
      { t: 'h2', text: 'Repair, replate or replace' },
      { t: 'p', text: 'Stainless and aluminium trim with minor dents and scratches can usually be straightened and polished, which is far cheaper than plating. Steel parts with light pitting are good replating candidates. Parts with deep pitting, previous poor repairs or corrosion through the base metal may cost more to restore than a good used original — worth checking the marque specialists before committing.' },
      { t: 'callout', kind: 'cost', title: 'Get quotes before you strip the car', text: 'Plating is priced per piece and by condition. Photograph your brightwork and obtain quotations early. Discovering the true cost after the car is in pieces is a common way for projects to stall.' },
    ],
    checklist: [
      'All brightwork sorted by material before quoting',
      'Parts photographed and inventoried, including small clips and fasteners',
      'Written quotations obtained from at least two platers',
      'Stainless and aluminium trim routed to polishing, not plating',
      'Good used originals priced as an alternative to restoration',
      'Restored parts stored wrapped and protected until final assembly',
    ],
    related: ['paint-preparation', 'parts-sourcing', 'glass-and-weatherstripping'],
  },
  {
    slug: 'glass-and-weatherstripping',
    title: 'Glass and Weatherstripping',
    summary:
      'Seals keep water out of the structure. Getting them right is corrosion prevention, not trim work.',
    stage: 'Interior',
    difficulty: 'Intermediate',
    image: 'thunderbird-56-blue',
    blocks: [
      { t: 'p', text: 'It is tempting to treat weatherstripping as a finishing detail. It is better understood as the system that determines whether the restoration you just paid for stays dry for the next thirty years. Almost every classic car rust pattern traces back to a failed seal.' },
      { t: 'h2', text: 'Where water actually gets in' },
      { t: 'ul', items: [
        'Windshield and rear window seals, particularly at the lower corners.',
        'Door and quarter window seals, and the vertical channels the glass runs in.',
        'Cowl vent seals, which drain directly onto the front floor pans when they fail.',
        'Trunk lid seals, which fill the spare wheel well slowly and invisibly.',
        'Blocked drain channels in doors and rockers, which turn a small leak into standing water.',
      ]},
      { t: 'h2', text: 'Glass' },
      { t: 'p', text: 'Original glass often carries a date code and manufacturer marking, which matters to originality-focused owners. Where original glass is sound, keep it — light scratching can often be polished out. Delamination at the edges of laminated windshields, or heavy pitting from decades of road use, are reasons to replace. Reproduction glass for popular models is available; for less common cars, good used glass may need to be sourced from specialists.' },
      { t: 'h2', text: 'Fitting seals well' },
      { t: 'ol', items: [
        'Clean the channel completely and address any corrosion before fitting anything.',
        'Test-fit the new seal dry, checking it follows the profile without stretching.',
        'Never stretch a seal to make it reach — it will shrink back and open a gap at a corner.',
        'Use the adhesive the manufacturer specifies, sparingly and in the right places.',
        'Confirm the drain paths behind the seal are clear before final fitting.',
        'Water-test the car afterwards, with someone inside looking for entry points.',
      ]},
      { t: 'callout', kind: 'safety', title: 'Windshield work is specialist work', text: 'Removing and fitting bonded or gasket-set glass without the right tools frequently breaks the glass and can cause serious cuts. Windshields also contribute to structural rigidity on many vehicles. Use an experienced automotive glass fitter.' },
    ],
    checklist: [
      'All seal channels cleaned and corrosion addressed before fitting',
      'New seals test-fitted dry and checked at corners',
      'No seal stretched to fit',
      'Drain paths in doors, rockers and cowl confirmed clear',
      'Original dated glass retained where it is sound',
      'Water test performed and entry points traced',
    ],
    related: ['interior-restoration', 'rust-inspection', 'storage-and-preservation'],
  },
  {
    slug: 'parts-sourcing',
    title: 'Parts Sourcing',
    summary:
      'Where parts for American classics actually come from, and how to buy them without duplicating spend.',
    stage: 'Parts & Planning',
    difficulty: 'Introductory',
    image: 'blog-parts',
    blocks: [
      { t: 'p', text: 'Parts availability varies enormously by model, and it is one of the strongest arguments for choosing a popular car for a first restoration. A 1965–70 Mustang can be assembled almost entirely from catalogue parts. A low-volume model of the same era may require hunting for years.' },
      { t: 'h2', text: 'The main channels' },
      { t: 'terms', items: [
        { term: 'Specialist reproduction suppliers', def: 'Catalogue businesses serving specific marques and models. Convenient, well documented, and the backbone of most restorations of popular cars.' },
        { term: 'New old stock (NOS)', def: 'Original factory parts never fitted to a vehicle. Correct in every detail and priced accordingly. Note that rubber and some plastics age in storage even when unused.' },
        { term: 'Used original parts', def: 'Salvage yards, marque specialists and enthusiast networks. Often the only source for trim and interior parts, and frequently better quality than reproductions.' },
        { term: 'Club and forum networks', def: 'Marque clubs and owner forums surface parts that never reach open sale, and provide the collective knowledge on which suppliers are worth using.' },
        { term: 'Swap meets and auto jumbles', def: 'Still the best route for obscure trim, and worth attending with a written list and reference photographs.' },
      ]},
      { t: 'h2', text: 'Buy in the right order' },
      { t: 'p', text: 'Order sheet metal and structural parts early, because they set the schedule and often have the longest lead times. Buy trim and interior parts when you find them rather than when you need them — scarcity, not budget, governs availability. Leave consumables and fluids to the end, because rubber, gaskets and fluids all have shelf lives.' },
      { t: 'callout', kind: 'note', title: 'Keep a parts ledger', text: 'Record every part with its supplier, part number, price and the date. It prevents duplicate ordering, makes returns straightforward, and forms part of the documentation that supports the car\'s value later.' },
      { t: 'h2', text: 'Judging a supplier' },
      { t: 'ul', items: [
        'Ask model-specific communities before ordering anything expensive.',
        'Check the returns policy before purchase, particularly for sheet metal that may not fit.',
        'Beware of listings that use manufacturer photographs but ship a different product.',
        'Inspect and test-fit parts as soon as they arrive, not months later when returns have closed.',
      ]},
    ],
    checklist: [
      'Model-specific parts availability researched before purchase of the car',
      'Structural and sheet metal parts ordered early',
      'Scarce trim bought when found rather than when needed',
      'Parts ledger maintained with supplier, number, price and date',
      'Every delivery inspected and test-fitted on arrival',
      'Returns policies confirmed before large orders',
    ],
    related: ['original-vs-reproduction-parts', 'restoration-budget-planning', 'evaluating-a-classic-car'],
  },
  {
    slug: 'original-vs-reproduction-parts',
    title: 'Original vs Reproduction Parts',
    summary:
      'When originality genuinely matters, when a reproduction is the better part, and how the choice affects value.',
    stage: 'Parts & Planning',
    difficulty: 'Introductory',
    image: 'blog-interior-restoration',
    blocks: [
      { t: 'p', text: 'This choice comes up dozens of times in a restoration, and the honest answer is that it depends on what the car is for. There is no universal right answer, but there is a right way to decide.' },
      { t: 'h2', text: 'When original matters most' },
      { t: 'ul', items: [
        'Cars being restored to a documented, factory-correct specification for judged competition.',
        'Rare or historically significant vehicles, where originality carries most of the value.',
        'Drivetrain components that establish a numbers-matching claim.',
        'Any component whose replacement would need to be disclosed in a future sale.',
      ]},
      { t: 'h2', text: 'When reproduction is genuinely better' },
      { t: 'ul', items: [
        'Safety-critical rubber and hydraulic components, where age is itself the defect.',
        'Wear items that were consumables when new, such as brake friction material and filters.',
        'Parts where new material outperforms a sixty-year-old original with no loss of authenticity.',
        'Anything on a car built to be driven regularly rather than judged.',
      ]},
      { t: 'h2', text: 'The middle ground' },
      { t: 'p', text: 'A common and sensible approach is to keep original parts that have been removed, fit reproductions where they make the car usable, and store the originals with the car. This preserves the option for a future owner to return the vehicle to original specification, and it is looked on favourably in the market. A box of labelled original parts that accompanies the car is a genuine asset.' },
      { t: 'callout', kind: 'caution', title: 'Reproduction quality is not uniform', text: 'Some reproduction parts match or exceed the original; others are visibly poorer in fit, finish and material. This varies by supplier and by part, not by category. Model-specific communities are the most reliable guide to which is which.' },
      { t: 'h2', text: 'On disclosure' },
      { t: 'p', text: 'Whatever you decide, record it. A restoration file that clearly states which components are original, which are NOS, which are reproduction and which have been rebuilt is the mark of a well-documented car — and it protects both you and any future buyer from misunderstandings.' },
    ],
    checklist: [
      'Purpose of the car decided before parts choices are made',
      'Drivetrain originality status established and documented',
      'Original removed parts retained, labelled and stored with the car',
      'Supplier reputation checked for each significant reproduction part',
      'Every substitution recorded in the restoration file',
    ],
    related: ['parts-sourcing', 'documentation-and-photography', 'restoration-budget-planning'],
  },
  {
    slug: 'restoration-budget-planning',
    title: 'Restoration Budget Planning',
    summary:
      'A framework for estimating a restoration honestly, and for deciding what standard you are actually building to.',
    stage: 'Parts & Planning',
    difficulty: 'Introductory',
    image: 'blog-budget',
    blocks: [
      { t: 'p', text: 'Restorations rarely fail because of one large unexpected expense. They fail because a series of reasonable-sounding decisions accumulate past the point the owner planned for. A budget is mainly a tool for noticing that happening early.' },
      { t: 'h2', text: 'Decide the standard first' },
      { t: 'p', text: 'These are genuinely different projects with different costs, and confusion between them is the most common budgeting error.' },
      { t: 'terms', items: [
        { term: 'Preservation', def: 'Keeping an original car as it is: mechanical safety and reliability addressed, patina retained. Usually the least expensive route and increasingly respected.' },
        { term: 'Driver quality', def: 'A presentable, reliable car that is honest about being used. Cosmetic imperfections tolerated where they do not affect function.' },
        { term: 'Show quality', def: 'Comprehensive restoration to a high cosmetic standard throughout, including areas not normally seen.' },
        { term: 'Concours', def: 'Restoration to documented factory specification, including finishes, markings and fasteners that most owners never notice. The most expensive by a wide margin.' },
      ]},
      { t: 'h2', text: 'Build the estimate in categories' },
      { t: 'p', text: 'Estimate each area separately rather than reaching for a single number. Purchase price; bodywork and rust repair; paint; engine; transmission and driveline; brakes and suspension; electrical; interior; brightwork and glass; wheels and tyres; consumables; and — importantly — tooling and workshop costs if you do not already have them.' },
      { t: 'h2', text: 'The unknowns are the budget' },
      { t: 'p', text: 'Bodywork is the category that moves, because you cannot see the whole problem until the car is stripped. A widely used approach is to obtain estimates for the work you can see, then hold a substantial contingency specifically for what stripping reveals. Restorers commonly describe adding a contingency of a third or more to the bodywork estimate; the right figure depends on how thoroughly you were able to inspect before buying.' },
      { t: 'callout', kind: 'cost', title: 'On published price figures', text: 'We do not publish current market values or restoration price tables. Costs vary enormously by region, by model, by shop rate and over time, and a number written today would mislead a reader next year. Obtain written quotations from shops in your own area, and consult current auction results and marque clubs for values.' },
      { t: 'h2', text: 'Time is part of the cost' },
      { t: 'p', text: 'A car occupying a garage for three years has a cost even when no money is being spent — in storage, in insurance, and in the tendency of stalled projects to deteriorate. Sequencing work so the car reaches a driveable state early, then improving it, keeps enthusiasm alive and is a legitimate strategy rather than a compromise.' },
    ],
    checklist: [
      'Target standard chosen explicitly and written down',
      'Separate estimate produced for each work category',
      'Written quotations obtained for bodywork, paint and machine work',
      'Explicit contingency held for what stripping reveals',
      'Tooling, storage and insurance included in the total',
      'Running total maintained against the original estimate',
      'Review point agreed at which the plan is reconsidered',
    ],
    related: ['evaluating-a-classic-car', 'parts-sourcing', 'documentation-and-photography'],
  },
  {
    slug: 'documentation-and-photography',
    title: 'Documentation and Photographing a Project',
    summary:
      'A restoration record is both a reassembly manual and a permanent part of the car\'s value.',
    stage: 'Parts & Planning',
    difficulty: 'Introductory',
    image: 'blog-documentation',
    blocks: [
      { t: 'p', text: 'Two things make documentation worth the effort. In the short term it is how you remember what a bracket looked like eighteen months ago. In the long term it is the evidence that the work was done, and done properly — which is precisely what a future buyer, an insurer or a judge wants to see.' },
      { t: 'h2', text: 'Photograph before you touch anything' },
      { t: 'p', text: 'The most valuable photographs are taken before disassembly begins, because that is the only moment the car still contains the answers. Shoot wide context views and close detail views of the same area, and include something for scale.' },
      { t: 'ul', items: [
        'Every panel and every panel gap, from a consistent set of angles.',
        'The engine bay as a whole, then each component, hose route, clip and label.',
        'The underside, before cleaning removes markings and paint daubs.',
        'The interior from every seating position, plus behind every trim panel as it comes off.',
        'All identification tags: VIN, body tag, engine and transmission stampings, axle codes.',
        'Any factory markings — inspection marks, grease pencil notes, paint daubs — which are often unrepeatable evidence of originality.',
      ]},
      { t: 'h2', text: 'Keep a written log' },
      { t: 'p', text: 'A dated log of what was done, by whom, with which parts, is the backbone of the file. Record the date, the work carried out, parts fitted with their numbers and suppliers, costs, and anything that surprised you. Include the decisions you made and why — a future owner reading that the original block was retained and sleeved, rather than replaced, learns something that no photograph shows.' },
      { t: 'h2', text: 'Store it so it survives' },
      { t: 'ul', items: [
        'Keep at least two copies in different physical locations, plus a cloud copy.',
        'Use plain, open file formats and a dated folder structure rather than a proprietary app.',
        'Keep original receipts and invoices — they establish both provenance and expenditure.',
        'Assemble a printed summary album to accompany the car.',
      ]},
      { t: 'callout', kind: 'note', title: 'Document honestly', text: 'A record that shows the repairs, the substitutions and the compromises is more credible and more useful than one that only shows the highlights. Buyers and judges trust complete records precisely because they include the unflattering parts.' },
    ],
    checklist: [
      'Comprehensive photography completed before disassembly',
      'All identification tags and factory markings recorded',
      'Fasteners bagged, labelled and photographed in place',
      'Dated written log maintained throughout',
      'Receipts and invoices retained and filed',
      'Backups held in at least two locations plus cloud storage',
      'Printed summary prepared to accompany the vehicle',
    ],
    related: ['original-vs-reproduction-parts', 'restoration-budget-planning', 'parts-sourcing'],
  },
  {
    slug: 'storage-and-preservation',
    title: 'Storage and Preservation',
    summary:
      'Keeping a restored or in-progress car from quietly undoing the work while it sits.',
    stage: 'Preservation',
    difficulty: 'Introductory',
    image: 'garage-service-bay',
    blocks: [
      { t: 'p', text: 'Cars deteriorate faster standing still than being used sensibly. Storage is an active discipline, not an absence of activity.' },
      { t: 'h2', text: 'The environment matters more than the building' },
      { t: 'p', text: 'The enemy is moisture, and specifically the cycle of condensation that occurs when temperature swings across the dew point. A dry, ventilated space with stable temperature protects a car better than a sealed, unheated garage where condensation forms on cold metal every morning. Concrete floors release moisture continuously; a vapour barrier under the car makes a measurable difference.' },
      { t: 'h2', text: 'Preparing a car to stand' },
      { t: 'ol', items: [
        'Wash and dry the car completely, including the underside, and address any paint damage.',
        'Change the oil before storage rather than after — used oil holds acidic combustion by-products.',
        'Fill or nearly fill the fuel tank to limit condensation in the tank, and consider a fuel stabiliser.',
        'Inflate tyres to their upper recommended pressure, and move the car periodically to avoid flat spots.',
        'Connect a quality battery maintainer, or remove the battery to a suitable location.',
        'Leave the parking brake off and chock the wheels, so shoes do not seize to drums.',
        'Use a breathable cover — never plastic sheeting, which traps moisture against the paint.',
      ]},
      { t: 'h2', text: 'Cars in mid-restoration' },
      { t: 'p', text: 'A stripped shell is far more vulnerable than a finished car. Bare metal must not be left unprotected — epoxy primer or an appropriate temporary coating goes on promptly. Store panels and trim wrapped, labelled and off the floor. Keep fasteners with their components, and keep the documentation somewhere that is not the workshop.' },
      { t: 'callout', kind: 'caution', title: 'Rodents are the underestimated risk', text: 'Mice and rats nest in air cleaners, seats and heater boxes, and chew wiring insulation with remarkable enthusiasm. A car stored without any rodent control can require a complete rewire after a single winter. Block obvious entry points and inspect regularly.' },
    ],
    checklist: [
      'Storage space assessed for humidity and ventilation',
      'Vapour barrier used over a concrete floor',
      'Oil changed immediately before storage',
      'Fuel tank filled and stabiliser considered',
      'Battery maintainer connected or battery removed',
      'Tyres inflated and vehicle moved periodically',
      'Parking brake released and wheels chocked',
      'Breathable cover in use, never plastic sheeting',
      'Rodent control in place and checked regularly',
    ],
    related: ['winter-storage', 'preparing-for-road-use', 'glass-and-weatherstripping'],
  },
  {
    slug: 'winter-storage',
    title: 'Winter Storage',
    summary:
      'What changes when a classic sits through a cold season, and how to bring it out again properly.',
    stage: 'Preservation',
    difficulty: 'Introductory',
    image: 'blog-storage',
    blocks: [
      { t: 'p', text: 'Seasonal storage is the norm for most classic owners in northern climates, and the routine is worth doing properly. The months a car spends parked are when most avoidable damage happens.' },
      { t: 'h2', text: 'Before it goes away' },
      { t: 'p', text: 'Everything in the general storage guide applies, with a few cold-weather additions. Check the coolant\'s freeze protection with a tester rather than assuming — a mix that was correct a decade ago may not be now, and a frozen block is a catastrophic, avoidable failure. Wash off any road salt thoroughly, including the underside, before the car is put away.' },
      { t: 'ul', items: [
        'Verify antifreeze concentration with a hydrometer or refractometer.',
        'Wash and dry the car completely, paying attention to wheel wells and the underside.',
        'Fill the fuel tank and add stabiliser if the car will stand more than a couple of months.',
        'Clean the interior thoroughly — food residue attracts rodents.',
        'Place moisture absorbers inside the cabin, and check them through the season.',
        'Crack a window very slightly if the storage space is dry and secure, to reduce interior humidity.',
      ]},
      { t: 'h2', text: 'During the season' },
      { t: 'p', text: 'Visit the car. A monthly check catches a failed battery maintainer, a fluid leak, or the first evidence of rodents while each is still a small problem. Opinions differ on whether to start a stored engine periodically: a brief start that never reaches full operating temperature can introduce more condensation into the oil and exhaust than it removes. If you do run it, run it long enough to reach full temperature, and preferably drive it.' },
      { t: 'h2', text: 'Bringing it back out' },
      { t: 'ol', items: [
        'Inspect underneath for fluid leaks and for evidence of rodent activity before anything else.',
        'Check the air cleaner and heater box for nesting material.',
        'Check all fluid levels and look closely at the brake fluid\'s condition.',
        'Inspect tyres for flat spots, cracking and correct pressures.',
        'Reconnect the battery and check charging before the first drive.',
        'Test the brakes at walking pace in a safe, private area before using the road.',
        'Drive gently for the first few miles, listening and watching temperature and pressure.',
      ]},
      { t: 'callout', kind: 'safety', title: 'Brakes first', text: 'Standing brakes can seize, and hydraulic seals can fail after months without movement. Always confirm braking at low speed off the public road before the first proper drive of the season.' },
    ],
    checklist: [
      'Antifreeze protection tested, not assumed',
      'Underside washed free of road salt',
      'Interior cleaned and moisture absorbers placed',
      'Battery maintenance arranged for the whole season',
      'Monthly inspection scheduled',
      'Rodent evidence checked before first start',
      'Fluids and tyres checked on recommissioning',
      'Low-speed brake test completed before road use',
    ],
    safety: 'Never run an engine in an enclosed space. Exhaust gas contains carbon monoxide, which is colourless, odourless and fatal.',
    related: ['storage-and-preservation', 'preparing-for-road-use', 'brake-system-restoration'],
  },
  {
    slug: 'preparing-for-road-use',
    title: 'Preparing a Restored Car for Road Use',
    summary:
      'The shakedown process that turns a finished restoration into a car you can actually rely on.',
    stage: 'Preservation',
    difficulty: 'Intermediate',
    image: 'blog-road-trip',
    blocks: [
      { t: 'p', text: 'A freshly restored car is not a proven car. Every system has been disturbed, and fasteners settle, seals bed in and adjustments drift during the first few hundred miles. The shakedown period is part of the restoration, not something that follows it.' },
      { t: 'h2', text: 'Before the first drive' },
      { t: 'ul', items: [
        'Re-torque critical fasteners: wheels, suspension, driveline and exhaust mounts.',
        'Check every fluid level and inspect underneath for leaks after the first run-up.',
        'Confirm every light, indicator and the horn actually work.',
        'Verify the brakes fully — pedal feel, travel, absence of pull, and a low-speed stop test off the road.',
        'Check tyre pressures and confirm the tyres themselves are not too old, regardless of tread depth.',
        'Have the alignment set to factory specification.',
      ]},
      { t: 'h2', text: 'Staged shakedown' },
      { t: 'ol', items: [
        'Short local runs first, staying close to home, watching temperature and oil pressure continuously.',
        'Return, let the car cool, and inspect underneath for leaks and for anything that has moved.',
        'Re-torque wheels and check suspension fasteners after the first fifty miles.',
        'Extend range progressively, adding highway speeds only once low-speed behaviour is settled.',
        'Carry out an oil change earlier than the normal interval after a rebuilt engine, as specified for the build.',
      ]},
      { t: 'h2', text: 'What to carry' },
      { t: 'p', text: 'A basic toolkit for the car\'s fastener sizes, spare drive belt and hoses, fluids, a torch, gloves, a fire extinguisher, and the workshop manual. Also a plan for what to do if it stops — breakdown cover that explicitly covers classic vehicles and flatbed recovery is worth confirming rather than assuming.' },
      { t: 'callout', kind: 'safety', title: 'Old tyres fail regardless of tread', text: 'Tyre rubber degrades with age. A tyre with full tread depth that is fifteen years old is not a safe tyre. Check the date code moulded into the sidewall and replace on age, not appearance. This matters enormously on classic cars that cover few miles.' },
      { t: 'callout', kind: 'note', title: 'Insurance and registration', text: 'Confirm that the vehicle is correctly registered and insured for road use, that the policy reflects the completed restoration\'s value, and that any modifications have been declared. Requirements differ by jurisdiction.' },
    ],
    checklist: [
      'Critical fasteners re-torqued before first drive',
      'Full lighting and horn function confirmed',
      'Brake system verified at low speed off the public road',
      'Tyre age checked from the sidewall date code',
      'Alignment set to factory specification',
      'Shakedown mileage completed in stages with inspections between',
      'Post-rebuild oil change carried out at the specified point',
      'Insurance, registration and recovery cover confirmed',
    ],
    safety: 'Do not use public roads to test unproven brakes or steering. Complete initial testing in a safe, private area, and have any work you cannot verify yourself inspected by a qualified professional.',
    related: ['brake-system-restoration', 'winter-storage', 'suspension-restoration'],
  },
]

export const getGuide = (slug: string) => guides.find((g) => g.slug === slug)

export const guideStages = [
  'Assessment',
  'Bodywork',
  'Mechanical',
  'Electrical',
  'Finishing',
  'Interior',
  'Parts & Planning',
  'Preservation',
] as const
